// Builds the room card (src/room-ui) into one self-contained HTML document and
// writes it as a string to src/lib/room/ui.generated.ts, which the MCP server
// returns as the ui:// resource and /room serves on the web. Run by `pnpm build`
// and by hand after editing src/room-ui: `node scripts/build-room-ui.mjs`.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build, transform } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const SRC = ['src/room-ui/room.ts', 'src/room-ui/room.css', 'scripts/build-room-ui.mjs'];

/** What the freshness test compares (tests/unit/room-mcp.test.ts): the card's own sources. */
export function sourceHash() {
  const h = createHash('sha256');
  for (const f of SRC) h.update(readFileSync(resolve(root, f)));
  return h.digest('hex').slice(0, 16);
}

export async function buildRoomUi() {
  const js = await build({
    entryPoints: [resolve(root, 'src/room-ui/room.ts')],
    bundle: true,
    format: 'iife',
    minify: true,
    target: 'es2020',
    write: false,
    tsconfig: resolve(root, 'tsconfig.json'),
    legalComments: 'none',
    logLevel: 'silent',
  });
  const css = await transform(readFileSync(resolve(root, 'src/room-ui/room.css'), 'utf8'), { loader: 'css', minify: true });
  const script = js.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><title>The room</title><style>${css.code}</style></head><body><div id="room"></div><script>${script}</script></body></html>`;
  const out = `// GENERATED by scripts/build-room-ui.mjs from src/room-ui. Do not edit; edit the sources and rebuild.\nexport const ROOM_UI_SOURCE_HASH = ${JSON.stringify(sourceHash())};\nexport const ROOM_UI_HTML: string = ${JSON.stringify(html)};\n`;
  writeFileSync(resolve(root, 'src/lib/room/ui.generated.ts'), out);
  return html.length;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const bytes = await buildRoomUi();
  console.log(`[room-ui] built ${bytes} bytes`);
}
