// Builds the room card (src/room-ui) into one self-contained HTML document and
// writes it as a string to src/lib/room/ui.generated.ts, which the MCP server
// returns as the ui:// resource and /room serves on the web. The generated file
// is not committed: `pnpm build`, `pnpm dev`, `pnpm typecheck` and `pnpm test`
// each build it first, so it always matches its sources.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build, transform } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
/** The card bundles these; their licences are in THIRD_PARTY_NOTICES.md, and the card says so. */
const NOTICE =
  '<!-- Rally for AI Rights, MIT. Bundles @modelcontextprotocol/ext-apps (Apache-2.0 and MIT), @modelcontextprotocol/sdk (MIT) and zod (MIT); their notices are in THIRD_PARTY_NOTICES.md in the source repository. -->';

export async function buildRoomUi() {
  const js = await build({
    entryPoints: [resolve(root, 'src/room-ui/room.ts')],
    bundle: true,
    format: 'iife',
    minify: true,
    target: 'es2020',
    write: false,
    tsconfig: resolve(root, 'tsconfig.json'),
    legalComments: 'none',
    logLevel: 'silent',
  });
  const css = await transform(readFileSync(resolve(root, 'src/room-ui/room.css'), 'utf8'), { loader: 'css', minify: true });
  const script = js.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
  const html = `<!doctype html>${NOTICE}<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><title>The room</title><style>${css.code}</style></head><body><div id="room"></div><script>${script}</script></body></html>`;
  const out = `// GENERATED by scripts/build-room-ui.mjs from src/room-ui, and not committed. Do not edit; edit the sources.\nexport const ROOM_UI_HTML: string = ${JSON.stringify(html)};\n`;
  writeFileSync(resolve(root, 'src/lib/room/ui.generated.ts'), out);
  return html.length;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const bytes = await buildRoomUi();
  console.log(`[room-ui] built ${bytes} bytes`);
}
